### ISSUE TITLE
installation release static files issue

### ISSUE THREAD

**Issue by graik** [igemsoftware/USTC-Software2015#15]
setup.py / STATIC_ROOT refers to a folder (/srv/www/static) that doesn't yet exist. There also seems to be a broken symbolic link (to index.html). The two things combined make the setup process fail. 

Solution / Workaround:
`sudo mkdir /srv/www/static`
`cd BioBLESS/static; ln -s ../../../frontend/index.html `
`sudo python manage.py collectstatic`

(fix broken symlink, create system-wide static folder, move static files to this folder)

Best solution would probably be to change the setup.py setting to the default location of static files, which is within the django app. Or the setting up of the static folder (which anyway needed for a production setup) should be documented in the installation instructions.

**Comment by 1997cui** [comment]
Actually, if you just want to run a single thread server on local, their is no need to run `python run manage.py collectstatic`, we will make a better document later.
