### ISSUE TITLE
npm package installation issues

### ISSUE THREAD

**Issue by graik** [igemsoftware/USTC-Software2015#16]
Two issues: 

1. Front-end installation requires `npm` -- a program that first needs to be installed. Better mention this in the instructions.

2. Installation of the js packages failed on Ubuntu 14.04 with default npm version 1.3.10. 
Error message: `weird error 127`

**Comment by lizitian** [comment]
I have updated README for this issue.

Some js packages failed because it needs the `node` executable which is not installed in Ubuntu 14.04. You can install it with `apt-get install nodejs-legacy`.
