### ISSUE TITLE
smaller installation issues

### ISSUE THREAD

**Issue by graik** [igemsoftware/USTC-Software2015#18]
There may be an issue with the virtualEnv activation script. On a Ubuntu 14.04 LT server edition virtual machine:
`run.sh` gives: `./run.sh: source: not found`

The manual instructions have a tiny glitch in that one has to call 'python manage.py' instead of './manage.py' (which was not executable). Most python devs will immideatly see this though. And most non-python devs will see that manage.py needs to be made executable, which is the other solution.

**Comment by graik** [comment]
one more thing: it would be good to clearly specify which Django version is expected.

**Comment by 1997cui** [comment]
We have fixed this bug in our master branch by switching to bash, rather than sh.
