### ISSUE TITLE
small change about result of simulation

### ISSUE THREAD

**Issue by Yishharu** [igemsoftware/USTC-Software2015#19]
curl 'https://ustc.software/simulate/' -H 'Origin: https://ustc.software' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: zh-CN,zh;q=0.8,en;q=0.6' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36' -H 'Content-Type: application/json' -H 'Accept: */*' -H 'Referer: https://ustc.software/BioBLESS/' -H 'X-Requested-With: XMLHttpRequest' -H 'Connection: keep-alive' --data-binary '{"nodes":["INPUT","INPUT","INPUT","NOT6","NOT6","NOT6","OR0","AND0","AND0","AND0","AND0"],"arcs":[{"to":8,"from":3},{"to":7,"from":4},{"to":9,"from":4},{"to":10,"from":5},{"to":4,"from":0},{"to":3,"from":1},{"to":10,"from":1},{"to":8,"from":2},{"to":5,"from":2},{"to":6,"from":7},{"to":7,"from":8},{"to":6,"from":9},{"to":9,"from":10}],"system_parameter":{"time":1000},"simulation_parameters":[{"device_parameter":{"initial":[10]}},{"device_parameter":{"initial":[10]}},{"device_parameter":{"initial":[10]}},{"e1":{"trans1":0.05,"trans2":0.05,"decay1":0.01,"decay2":0.01},"e2":{"reg":0.5},"e3":{"reg":0.5},"e4":{"trans1":0.05,"trans2":0.05,"decay1":0.01,"decay2":0.01},"device_parameter":{"initial":[10,10]}},{"e1":{"trans1":0.05,"trans2":0.05,"decay1":0.01,"decay2":0.01},"e2":{"reg":0.5},"e3":{"reg":0.5},"e4":{"trans1":0.05,"trans2":0.05,"decay1":0.01,"decay2":0.01},"device_parameter":{"initial":[10,10]}},{"e1":{"trans1":0.05,"trans2":0.05,"decay1":0.01,"decay2":0.01},"e2":{"reg":0.5},"e3":{"reg":0.5},"e4":{"trans1":0.05,"trans2":0.05,"decay1":0.01,"decay2":0.01},"device_parameter":{"initial":[10,10]}},{"e1":{"trans1":0.1,"trans2":0.1,"decay1":0.02,"decay2":0.02},"e2":{"reg":2},"e3":{"reg":2},"e4":{"reg":2},"e5":{"trans1":0.1,"trans2":0.1,"decay1":0.02,"decay2":0.02},"device_parameter":{"initial":[10,10]}},{"e1":{"trans1":0.05,"trans2":0.05,"decay1":0.01,"decay2":0.01},"e2":{"reg":0.5},"e3":{"reg":0.5},"device_parameter":{"initial":[10]}},{"e1":{"trans1":0.05,"trans2":0.05,"decay1":0.01,"decay2":0.01},"e2":{"reg":0.5},"e3":{"reg":0.5},"device_parameter":{"initial":[10]}},{"e1":{"trans1":0.05,"trans2":0.05,"decay1":0.01,"decay2":0.01},"e2":{"reg":0.5},"e3":{"reg":0.5},"device_parameter":{"initial":[10]}},{"e1":{"trans1":0.05,"trans2":0.05,"decay1":0.01,"decay2":0.01},"e2":{"reg":0.5},"e3":{"reg":0.5},"device_parameter":{"initial":[10]}}]}' --compressed

**Comment by 1997cui** [comment]
fixed
